version: '3.3'
services:
  mysqldb:
    image: "mysql"
    restart: always
    ports:
      - 3307:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: person_manager
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_ROOT_HOST: '%'
networks:
  springapimysql-net: